// Code generated by "make version". DO NOT EDIT.

package api

const Version = "18.2.6"

const VersionMajor = 18
const VersionMinor = 2
const VersionPatch = 6
const VersionPreRelease = ""
const VersionMetadata = ""
